package timeline;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;

public class EditEvent extends javax.swing.JFrame {

    /**
     * Creates new form EditEvent
     */
    private Event event;
    private Category selectedCategory;
    private Timeline timeline;
    private EditTimeline superTimeline;
    private EditEvent thisEditEvent;
    
    public EditEvent(Event event, FileIO fileIO, Timeline timeline, EditTimeline superTimeline) {
        this.event = event;
        this.fileIO = fileIO;
        this.timeline = timeline;
        this.superTimeline =superTimeline;
        thisEditEvent = this;
        initComponents();
    }

    private final FileIO fileIO;
    private JButton finishedButton;
    private JComboBox jComboBox1;
    private JLabel titleLabel;
    private JTextField nameTextField;
    private JTextArea descriptionTextArea;
    private JTextField startTextField;
    private JTextField endTextField;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setResizable(false);
        
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int y = (int) ((d.getHeight() - getHeight()) / 2);        
        int x = (int) ((d.getWidth() - getWidth()) / 2);
        setLocation(x, y);
        
        titleLabel = new JLabel();
        nameTextField = new JTextField();
        descriptionTextArea = new JTextArea();
        descriptionTextArea.setPreferredSize( new Dimension( 100, 136 ) );
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setWrapStyleWord(true);

        
        startTextField = new JTextField();
        endTextField = new JTextField();
        jComboBox1 = new JComboBox();
        finishedButton = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        try{
            titleLabel.setFont(new Font("Vijaya", 0, 42));
        }catch(Exception e){
            titleLabel.setFont(new Font("Times new Roman", 0, 34));
        }
        titleLabel.setText("Edit Event");

        fillTextFields();
        setComboBox();
        
        jComboBox1.addActionListener(new ComboBoxListener());

        finishedButton.setText("Finished");
        finishedButton.addActionListener(new EEListener());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLabel)
                    .addComponent(nameTextField)
                    .addComponent(startTextField)
                    .addComponent(endTextField)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finishedButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descriptionTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)    
                .addComponent(descriptionTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)    
                )
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)     
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(startTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(endTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(finishedButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fillTextFields(){
        if(event.getTitle()!=null)
            nameTextField.setText(event.getTitle());
        else
            nameTextField.setText("<Name>");
        if(event.getDescription()!=null)
            descriptionTextArea.setText(event.getDescription());
        else
            descriptionTextArea.setText("<Des>");
        if(event.getStartDate()!=null)
            startTextField.setText(""+event.getStartDate());
        else
            startTextField.setText("<Start>");
        if(event.getEndDate()!=null)
            endTextField.setText(""+event.getEndDate());  
        else
            endTextField.setText("<End>");
    }
    
    public void setComboBox(){
        Iterator<Category> categoryIterator =  fileIO.getCategoryIterator();
        String[] names = new String[fileIO.catSize()+1];
        int i = 0;
        int catIndex = 0;
        Category c = new Category("Base");
        while(categoryIterator.hasNext()){
            c = categoryIterator.next();
            names[i++] = c.getName();
        }
        names[i] = "New Category";
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(names));
        selectedCategory = c;
        jComboBox1.setSelectedItem(event.getCategory().getName());
    }
    
    // Returns true if valid event, false if not.
    public boolean submitTextFields(){
        String name = nameTextField.getText();
        String description = descriptionTextArea.getText();
        System.out.println(descriptionTextArea.getText());
        String startDate = startTextField.getText();
        String endDate = endTextField.getText();
        Integer start, end;
        //Name and startDate are essential descriptors. The others are optional.
        if(name.equals("<Name>") || startDate.equals("<Start>")){
            //Note: inform user they're wrong first.
            return false;
        }
        try{
            start = Integer.parseInt(startDate);
        }catch(NumberFormatException e){
            System.out.println("Invalid start date!");
            return false;
        }
        
        event.setTitle(name);
        event.setStartDate(start);
        event.setCategory(selectedCategory);
        
        if(!description.equals("<Des>")){
            event.setDescription(description);
        }
        if(!endDate.equals("<End>")){
            try{
                end = Integer.parseInt(endDate);
            }catch(NumberFormatException e){
                System.out.println("Invalid end date!");
                return false;
            } 
            //The end date can't happen before the starting date!
            if(end >= start) event.setEndDate(end);
        }
        return true;
    }

    private class EEListener implements ActionListener{
    
        public EEListener(){
        }
    
        public void actionPerformed(ActionEvent ae){
            JButton thisButton = (JButton) ae.getSource();
            if(thisButton == finishedButton){
                if(submitTextFields()){
                    timeline.addEvent(event);
                    superTimeline.setComboBox();   
                    fileIO.save();
                }
                setVisible(false);
                dispose();
            }
        }
    
    }
    
    private class ComboBoxListener implements ActionListener{
    
    public ComboBoxListener(){
        
    }
    
    public void actionPerformed(ActionEvent ae){
        JComboBox thisBox = (JComboBox) ae.getSource();
        
        if(thisBox.getSelectedItem().equals("New Category")){
              java.awt.EventQueue.invokeLater(new Runnable() {
                   public void run() {
                        new EditCategory(selectedCategory, fileIO, thisEditEvent).setVisible(true);
                   }
               });
               
               setComboBox(); // Reset combo box to display the new timeline.
               return;
        }
        
        Iterator<Category> categoryIterator =  fileIO.getCategoryIterator();
        Category c;
        while(categoryIterator.hasNext()){
            c = categoryIterator.next();
            if(thisBox.getSelectedItem().equals(c.getName())){
                selectedCategory = c;
                break;
            }            
        }
    }

    }
}