
import java.awt.Component;
import java.awt.*;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.*;
import javax.swing.JComboBox;

public class ManageCategories extends javax.swing.JFrame {

    /**
     * Creates new form ManageCategories
     */
    private final FileIO fileIO;
    private Category selectedCategory;

    public ManageCategories(FileIO fileIO) {
        this.fileIO = fileIO;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private JButton editButton;
    private JButton createButton;
    private JButton deleteButton;
    private JComboBox jComboBox1;
    private JLabel titleLabel;
    private JTextField nameTextField;
    
    private void initComponents() {
        setResizable(false);
        
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int y = (int) ((d.getHeight() - getHeight()) / 2);        
        int x = (int) ((d.getWidth() - getWidth()) / 2);
        setLocation(x, y);
        
        titleLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setText("Manage Categories");
        
        try{
            titleLabel.setFont(new Font("Vijaya", 0, 42));
        }catch(Exception e){
            titleLabel.setFont(new Font("Times new Roman", 0, 34));
        }
        
        setComboBox();
        
        editButton.setText("Edit Category");
        deleteButton.setText("Delete Category");
        createButton.setText("Create Category");
        nameTextField.setText("<Name>");
        
        editButton.addActionListener(new MCListener());
        deleteButton.addActionListener(new MCListener());
        createButton.addActionListener(new MCListener());
        
        jComboBox1.addActionListener(new ComboBoxListener());

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(titleLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createButton, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)))
                            ))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))    
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton))
                .addComponent(deleteButton)
)
        );
       
        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void setComboBox(){
        Iterator<Category> categoryIterator =  fileIO.getCategoryIterator();
        String[] names = new String[fileIO.catSize()];
        int i = 0;
        Category c = new Category("Base");
        while(categoryIterator.hasNext()){
            c = categoryIterator.next();
            names[i++] = c.getName();
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(names));
        selectedCategory = c;
    }
        
    private class MCListener implements ActionListener{

        public MCListener(){
        }

        public void actionPerformed(ActionEvent ae){
            JButton thisButton = (JButton) ae.getSource();
            if(thisButton == editButton){
                if(fileIO.catSize()==1) return;
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new EditCategory(selectedCategory).setVisible(true);
                }
            });

           }else if(thisButton == deleteButton){
               if(fileIO.catSize()>1){
                   fileIO.deleteCategory(selectedCategory);
                   setComboBox();
               }

           }else if(thisButton == createButton){
               String name = nameTextField.getText();
               if(name.equals("<Name>")) return;
               Category cat = new Category(name);
               fileIO.addCategory(cat);
               setComboBox(); // Reset combo box to display the new timeline.
               jComboBox1.setSelectedItem(cat.getName());
               selectedCategory = cat;
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new EditCategory(selectedCategory).setVisible(true);
                }
            });
               
           }
        }

        }

    private class ComboBoxListener implements ActionListener{

        public ComboBoxListener(){

        }

        public void actionPerformed(ActionEvent ae){
            JComboBox thisBox = (JComboBox) ae.getSource();
            Iterator<Category> categoryIterator =  fileIO.getCategoryIterator();
            Category c;
            while(categoryIterator.hasNext()){
                c = categoryIterator.next();
                if(thisBox.getSelectedItem().equals(c.getName())){
                   selectedCategory = c;
                   break;
               }            
            }
        }

    }    
    
    
}