
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;

public class ManageTimelines extends javax.swing.JFrame {

    /**
     * Creates new form ManageTimelines
     */
    private FileIO fileIO;
    private Timeline selectedTimeline = new Timeline("Base");
    
    public ManageTimelines(FileIO fileIO) {
        this.fileIO = fileIO;
        initComponents();
    }
    
    private javax.swing.JButton manageButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField nameTextField;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        titleLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        manageButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        
        manageButton.addActionListener(new MTListener());
        createButton.addActionListener(new MTListener());
        deleteButton.addActionListener(new MTListener());
        
        jComboBox1.addActionListener(new ComboBoxListener());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setText("Manage Timelines");

        setComboBox();

        manageButton.setText("Edit Timeline");
        createButton.setText("Create Timeline");
        nameTextField.setText("<Name>");
        deleteButton.setText("Delete Timeline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(titleLabel)
                                .addGap(75, 75, 75)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        
                try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTimelines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTimelines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTimelines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTimelines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }// </editor-fold>//GEN-END:initComponents

/*
    Sets all the combo box options with all the timelines
    available and known to the FileIO object.
    
    */
private void setComboBox(){
    Iterator<Timeline> timelineIterator =  fileIO.getTimelineIterator();
    String[] names = new String[fileIO.timeSize()+1];
    int i = 1;
    names[0] = "All Timelines";
    Timeline t = new Timeline("Base");
    while(timelineIterator.hasNext()){
        t = timelineIterator.next();
        names[i++] = t.getTitle();
    }
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(names));
    
}
     
private class MTListener implements ActionListener{
    
    public MTListener(){
    }
    
    public void actionPerformed(ActionEvent ae){
        JButton thisButton = (JButton) ae.getSource();
        if(thisButton == manageButton){
            if(selectedTimeline.getTitle().equals("Base")) return;
            /* Create and display the form */
            titleLabel.setText("manage");
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTimeline(selectedTimeline, fileIO).setVisible(true);
            }
        });

       }else if(thisButton == deleteButton){
           titleLabel.setText("delete");
           if(!selectedTimeline.getTitle().equals("Base")){
               fileIO.deleteTimeline(selectedTimeline);
               setComboBox();
           }
           
       }else if(thisButton == createButton){
           String name = nameTextField.getText();
           if(name.equals("<Name>")) return;
           Timeline time = new Timeline(name);
           fileIO.addTimeline(time);
           setComboBox(); // Reset combo box to display the new timeline.
           jComboBox1.setSelectedItem(time.getTitle());
           selectedTimeline = time;
       }
    }
    
    }

private class ComboBoxListener implements ActionListener{
    
    public ComboBoxListener(){
        
    }
    
    public void actionPerformed(ActionEvent ae){
        JComboBox thisBox = (JComboBox) ae.getSource();
        
        Iterator<Timeline> timelineIterator =  fileIO.getTimelineIterator();
        Timeline t;
        while(timelineIterator.hasNext()){
            t = timelineIterator.next();
            if(thisBox.getSelectedItem().equals(t.getTitle())){
                selectedTimeline = t;
                break;
            }            
        }
    }
    
}


}
    


